In [78]:
import itertools
import numpy as np
from scipy.spatial import distance
from scipy.spatial.distance import cdist
import math

### Generate Permutation set

In [52]:
y = [i for i in range(1, 10)]
print(y)

y_p = list(iter(itertools.permutations(y,9)))
print(len(y_p))

[1, 2, 3, 4, 5, 6, 7, 8, 9]
362880


### Calculate Hamming Distance

In [182]:
hammin_distance = distance.hamming( y_p[1234], y_p[0])
print(hammin_distance)

ValueError: The 1d arrays must have equal lengths.

### uniform sampling

In [67]:
num_perm = 10
perm_list = np.random.randint(1, math.factorial(9),size=num_perm)
perm_list

array([116173, 354492, 287907,  76632,  85156, 345848, 275761, 171318,
       107087, 319070])

### Generate min or max hammin distance permute

In [176]:
from tqdm import tqdm

In [194]:
P_hat = np.array(list(itertools.permutations(list(range(1,10)), 9)))
np.random.shuffle(P_hat)
n = 50

for i in tqdm(range(0, n)):
    
    # 첫 번째에는 아무것도 없는 빈 리스트에 값을 넣음
    if i==0:
        # 랜덤한 값 1개를 뽑음
        j = np.random.randint(n)
        # 리스트에 추가 및 shape 변경. (9, ) => (1, 9)
        P = np.array(P_hat[j]).reshape([1,-1])
    else:
        # 두 번째부터는 원래 있던 리스트에 concat 해줌 . shape (1, 9) => (2, 9) => (3, 9) => ... =>(n-1, 9)
        P = np.concatenate([P,P_hat[j].reshape([1,-1])],axis=0)

    # 뽑은 값은 리스트에서 삭제
    P_hat = np.delete(P_hat,j,axis=0)
    
    # P 리스트에 있는 모든 값과 P_hat에 있는 모든 값을 비교하여 distance를 얻음
    # P 리스트의 shape이 (4, 9) 라고하면 (4, P_hat.shape[0] - 4) 가됨.
    # 이걸 mean 하여 1개의 list로 변경 => D의 shape (P_hat.shape[0] - 4, )
    D = cdist(P,P_hat, metric='hamming').mean(axis=0).flatten()
    
    # 만약 Max distance를 구한다면
    if False :
        j = D.argmax()

    # 만약 Min distance를 구한다면
    else :
#         j = D.argmin()
        m = int(D.shape[0]/2)
        # 오름차순 정렬
        S = D.argsort()
        j = S[np.random.randint(m-10,m+10)]
        

100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:11<00:00,  4.43it/s]


In [195]:
for i in P :
    print(i)

[7 2 3 1 5 8 9 6 4]
[8 1 5 9 7 2 4 6 3]
[2 6 5 1 4 9 3 8 7]
[2 8 7 9 1 4 3 5 6]
[3 9 1 6 2 8 4 5 7]
[3 5 2 1 6 4 9 7 8]
[1 3 4 9 6 5 2 8 7]
[1 7 9 8 6 3 4 5 2]
[7 1 4 6 3 8 9 2 5]
[6 2 8 5 1 4 3 9 7]
[1 4 9 6 3 5 7 8 2]
[5 4 7 6 8 1 3 9 2]
[4 7 6 5 1 2 3 9 8]
[5 4 8 1 6 3 2 7 9]
[5 7 3 1 2 9 8 6 4]
[1 5 2 7 8 3 4 6 9]
[3 2 1 6 9 5 8 7 4]
[6 2 7 3 8 9 4 5 1]
[4 3 5 7 8 9 1 6 2]
[4 1 2 9 3 5 6 7 8]
[5 1 7 9 2 8 6 4 3]
[2 6 4 5 3 8 1 7 9]
[2 1 7 5 4 6 8 9 3]
[1 3 7 2 6 9 5 4 8]
[4 3 9 6 2 7 8 5 1]
[8 1 6 2 5 4 3 7 9]
[4 1 5 3 7 2 8 9 6]
[5 2 1 9 7 6 4 3 8]
[9 1 2 7 6 4 5 3 8]
[1 3 9 4 5 2 7 6 8]
[4 2 9 8 7 3 6 5 1]
[4 3 5 2 1 7 6 8 9]
[5 6 9 4 2 1 8 7 3]
[4 8 5 7 1 6 2 9 3]
[4 3 1 7 9 2 5 8 6]
[5 8 7 4 6 9 1 2 3]
[5 9 4 2 6 8 3 1 7]
[4 5 1 3 8 7 6 9 2]
[6 3 2 7 5 4 8 1 9]
[2 1 7 3 4 5 9 8 6]
[7 3 8 1 4 5 2 6 9]
[4 8 2 9 7 6 3 1 5]
[5 7 9 2 1 6 8 3 4]
[7 8 4 3 6 5 2 9 1]
[8 7 4 2 6 3 5 9 1]
[8 5 1 9 2 3 4 7 6]
[2 6 8 1 7 5 4 3 9]
[7 8 5 9 2 3 6 4 1]
[6 7 1 2 9 8 4 5 3]
[6 2 8 4 1 5 7 9 3]
